#Your directory in XXX
dat1<-read.csv("XXX/EUEU_EUIB.csv",sep=";")
dat2<-read.csv("XXX/EUEU_EUIT.csv",sep=";")
dat3<-read.csv("XXX/EUEU_IBIB.csv",sep=";")
install.packages("lme4")
install.packages("car")
library("lme4")
library("car")

#LMMs
m1<-lmer(Gen_dist~Comparative+Geo_dist+N_max+(1|Species),data=dat1)
Anova(m1)
m2<-lmer(Gen_dist~Comparative+Geo_dist+N_max+(1|Species),data=dat2)
Anova(m2)
m3<-lmer(Gen_dist~Comparative+Geo_dist+N_max+(1|Species),data=dat3)
Anova(m3)

#GMYC
install.packages("ape")
install.packages("MASS")
install.packages("paran")
install.packages("splits",repos="http://R-Forge.R-project.org")
library(ape)
library(MASS)
library(paran)
library(splits)
Mytree<-read.nexus("Directory of the file generated by TreeAnotator")
Test1<-gmyc(Mytree,method=”single”)
pdf(file=”gmycresults”,height=70) #adjust ‘height’
plot(Test1)
dev.off()
